### PR TITLE
feat(authentication): add authentication to the template

### PR DESCRIPTION
**Pull request by harish-aka-shivi**
### Description
This PR adds the following features to the template:
- add the authentication
- create components that are required to show the demo.

### Check List
If not relevant to pull request, check off as complete

- [x] All tests passing
- [ ] Docs updated with any changes or examples if applicable
- [x] Added tests to ensure new feature(s) work properly

### Relevant Issues

#7

### CODE REVIEW

**Comment by harish-aka-shivi** [comment]
Note: This branch has originated from #5. I need to rebase it before merging in the master. As #5 has not been merged yet, so I am waiting for that to be merged before. 
However, please review it so that things can move in parallel. 🙂

**Comment by harish-aka-shivi** [comment]
auth

**Comment by harish-aka-shivi** [comment]
@prescottprue, Please review this.

**Comment by harish-aka-shivi** [comment]
@prescottprue 
I understand there are a lot of file changes. I couldn't figure out any other way.
If you can merge #5 please do that first, then this will be easy to review as I will rebase it to the master.
Thanks 🙂

**Review by prescottprue — APPROVED** [review]

**Pull request merged**
